### PR TITLE
[Draft] Add test script to visualize walkers and pygame environment, fix galloper and wheel walker typos

### PR DESCRIPTION
**Pull request by daia99**

### CODE REVIEW

**Comment by herbiebradley** [comment]
Thanks for this! Can you move the visualisation requirements to pyproject.toml? That way people can do say `pip install openelm[sodaracer]` or `pip install -e .[sodaracer]` to get the pygame install and we don't need a separate file.

**Comment by daia99** [comment]
Thanks for your suggestion! I moved the pygame optional requirement to the file, and cleaned up the readme instructions

**Comment by herbiebradley** [comment]
Thanks for including the framework backend! Can you remove the redundant files that do not use the pygame backend, since they almost certainly won't be used. For example, as far as I can see the actual `simulator.py` visualization only includes classes and functions from `framework.py`, `settings.py`, and the `pgu/gui` directory.

**Comment by daia99** [comment]
Will look into this! Was thinking on the topic about the potential for expansions to OpenELM to require other unforeseen module imports in the box2d example (for the dependency fix) which may require currently unused import sources, but it does make sense to trim down repos if possible.

**Comment by herbiebradley** [comment]
> Will look into this! Was thinking on the topic about the potential for expansions to OpenELM to require other unforeseen module imports in the box2d example (for the dependency fix) which may require currently unused import sources, but it does make sense to trim down repos if possible.

Yeah, I'm just not sure that we need additional imports for the foreseeable future, unless you find something wrong with the existing visualization code. I expect going forward to mostly focus OpenELM away from Sodaracers towards a wider set of domains, most of which probably won't require box2d at all.

**Comment by daia99** [comment]
image
image
image

Saving visualization of sodaracers (from top to bottom: runner, galloper, wheel).

Runner and wheel are static, but galloper is moving. joints fall mysteriously from galloper to the ground.

Seed functions seem visually fine:
image
image
image
image

CPPN_mutable (last screenshot) is only one I'm unsure about

**Comment by herbiebradley** [comment]
Thanks for the PR, this really needed fixing!

**Pull request merged**
